#
# Module manifest for module 'WriteProgressPlus'
#
# Generated by: Maciej Krosta
#
# Generated on: 10.02.2024
#

@{

    # Script module or binary module file associated with this manifest.
    #RootModule = 'WriteProgressPlus.dll'

    # Version number of this module.
    ModuleVersion      = '0.0.1' # placeholder 

    # Supported PSEditions
    CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID               = '19da6c54-8e49-4a5f-b424-4ba6e3500783'

    # Author of this module
    Author             = 'Maciej Krosta'

    # Company or vendor of this module
    CompanyName        = ''

    # Copyright statement for this module
    Copyright          = '(c) Maciej Krosta. All rights reserved.'

    # Description of the functionality provided by this module
    Description        = @'
Extension of the standard WriteProgress, which simplifies control, automates its functionalities and extends its capabilities, including support for in-pipeline placement.

Functionalities of this module include:
- Updating progress bars directly from pipeline (without having to use ForEach-Object).
- Keeping track of current iteration automatically (with specified increment).
- Automatic calculation of percent done and time remaining (when provided total count).
- Option to include current iteration, total count and percent done in Status message.
- Ability to provide current object to be displayed in Status or CurrentOperation (item format can be customized).
- Support for both classic and minimal style of progress bar.
- State of progress bar can be kept between commands or cleared, depending on requirements.
- Support for child progress bars.
'@

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion  = '3.0'

    # Name of the PowerShell host required by this module
    PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    DotNetFrameworkVersion = '4.6.1' # lowest version compliant with netstandard2.0

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    ProcessorArchitecture = 'None'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    ScriptsToProcess = @() # placeholder 

    # Type files (.ps1xml) to be loaded when importing this module
    TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport  = @()

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport    = @() # placeholder 

    # Variables to export from this module
    VariablesToExport = @() 

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport    = @() # placeholder 

    # DSC resources to export from this module
    DscResourcesToExport = @()

    # List of all modules packaged with this module
    ModuleList = @()

    # List of all files packaged with this module
    FileList = @() # placeholder 

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData        = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('Progress', 'ProgressBar', 'Write-Progress')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/Pedrokostam/WriteProgressPlus/blob/main/LICENSE.txt'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Pedrokostam/WriteProgressPlus'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = 'https://github.com/Pedrokostam/WriteProgressPlus/blob/master/CHANGELOG.md'

            # Prerelease string of this module
            # Prerelease = 'false'

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    DefaultCommandPrefix = ''

}

